### PR TITLE
Added my programming small group

### PR DESCRIPTION
**Pull request by mclark4386**
The plan is to have it be a running small group that meets every semester. This semester we are meeting in the MM conference room on Mondays at 6pm. Please sign up via the link!

### CODE REVIEW

**Comment by wad3g** [comment]
@mclark4386 Do you mind updating the link to *your* specific group (https://groups.highlandsapp.com/groups/computer-programming-spring-2018) rather than a query for "computer programming"?

Also, sorry for the delay responding to this. Just wanted think about it for a bit before pulling the trigger.

I'd like for this resource to be some of the larger resources/groups in Birmingham without overloading it with extremely small and/or stale items, but couldn't come up with a good decision to draw the line on what does/doesn't belong. 

Does this make sense? Could really use some input/feedback on this.

**Comment by mclark4386** [comment]
Sure, no problem. Take care!

**Comment by wad3g** [comment]
@mclark4386 I didn't mean close it! Ha, just update the link.

Was mainly seeing if you had any thoughts on how to best include groups without over bloating the list.

**Comment by mclark4386** [comment]
Ooooh, misunderstood! Maybe have a second page for smaller meetups/groups? I was actually expecting that, but when it was all one file I didn't want to change the entire format just for my group^^;

**Comment by mclark4386** [comment]
Good call on the link btw, I think because I'm the leader it doesn't have that link for me^^;

**Comment by wad3g** [comment]
@mclark4386 if smaller meetups/groups were on another page would that mean each category were on a second page or just an additional page for groups? The OCD in me would prefer it to be uniform, but I think I'd still lean towards the latter. Primarily so _most_ resources would still be easily 
accessible on the README/GitHub.

**Comment by mclark4386** [comment]
Fair enough. It's a nebulous thing to format^^ Thanks for adding the group!

**Pull request merged**
