### PR TITLE
Added Bham! Game Developers to README.md

### PR DESCRIPTION
**Pull request by ghouston**
* added facebook link for Bham! Game Developers under Groups and Organizations
* added slack link for Bham! Game Developers under Discussion > Slack

### CODE REVIEW

**Comment by wad3g** [comment]
@ghouston I'm waiting on a response to #6 before merging. 

Personally, I think we should stick to _only_ public Slack channels. Thoughts?

If they'd like to have/be a public channel, but need a signup we could easily just offer one similar to https://wg-auto-invite.herokuapp.com/.

**Comment by ghouston** [comment]
@wad3g 
Thanks for pointing out the auto invite.  I think that is a good idea to speed adding people to a slack group.  Where is the source code? I will pass it on to the leaders of Bham Game Devs.

I am not a leader of the group, just a participant.  It is a good group.  I am sure the signup is like it is because that is the default for slack.

I don’t think you should require “public” groups.   Your list is already full of “private” entities.  The most similar example is Magic City Tech which has the same signup process as BGD.  So you would have to drop them from your list as well if “public”/automated sign-up is required.  Your list’s value is connecting people and entities.  You don’t need to limit the list based on a groups policies and processes.  That makes you into a gatekeeper and limits the value of your list.  Remember a lot of user groups are small and run by volunteers.  So you shouldn’t put demands on them.  Instead list them and help them grow.

**Comment by wad3g** [comment]
@ghouston

Ahh, you're right. 

Source was over on BitBucket, but just created a [repo](https://github.com/wad3g/better-slack-invite-automation). 

It's a fork of [slack-invite-automation](https://github.com/outsideris/slack-invite-automation) with minor changes since the original wasn't responsive/looked dated.

**Comment by wad3g** [comment]
@ghouston here's a link if you want to update the PR:

https://bhamgamedevs.herokuapp.com

**Pull request closed without merging**
